# Generated by Django 4.2.17 on 2025-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Shows', 'TV Shows'), ('Anime', 'Anime')], default='k', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
