# Generated by Django 4.2.17 on 2025-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_category_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
